### ISSUE TITLE
cashpw/agenda-with-archives not found

### ISSUE THREAD

**Issue by labe-me** [cashpw/clocktable-by-category#3]
Hello,

The doc suggests to use cashpw/agenda-with-archives but this function is not provided by the package.

Thanks

**Comment by cashpw** [comment]
I included `:files` and `:files-fn` to allow for `clocktable` based on a list of files which are different than the user's `org-agenda-files`. For example, I use [`cashpw/org-clock--agenda-with-archives`](https://github.com/cashpw/dotfiles/blob/main/config/doom/config-personal.org?plain=1#L6945-L6952) to return a specific list of files.

You can omit `:files-fn` and instead use [`clocktable`'s built-in `:scope` property](https://orgmode.org/manual/The-clock-table.html) if you want to include your `org-agenda-files` and the relevant `*.org_archive` files:

```org
#+BEGIN clocktable-by-category :scope agenda-with-archives
#+END
```
