### ISSUE TITLE
ARCHIVE_CATEGORY

### ISSUE THREAD

**Issue by labe-me** [cashpw/clocktable-by-category#4]
Hello again,

I could not make it work with archived content.

the properties of archived items are renamed like this:

```
:PROPERTIES:
...
:ARCHIVE_CATEGORY: MyCategory
:END:
```

Was looking for a way to fix the code to support the ARCHIVE_CATEGORY property and make a PR but sadly my emacs-lisp fu is not strong enough :)

**Comment by cashpw** [comment]
Thanks for catching this! I had fixed it locally and hadn't uploaded the fix.

**Comment by labe-me** [comment]
Fantastic, thank you!
